mcm_demo_homepage:
    path:     /hello/{name}
    defaults: { _controller: MCMDemoBundle:Default:index }

mcm_demo_ex3:
    path:     /text
    defaults: { _controller: MCMDemoBundle:Sometext:index }
