mcm_demo_ex2:
    resource: "@MCMDemoBundle/Controller/"
    type:     annotation
    prefix:   /article


mcm_demo_homepage:
    path:     /hello/{name}
    defaults: { _controller: MCMDemoBundle:Default:index }

mcm_demo_ex3:
    path:     /text
    defaults: { _controller: MCMDemoBundle:Sometext:index }



