<?php

namespace MCM\DemoBundle\Entity;

/**
 * FsnameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FsnameRepository extends \Doctrine\ORM\EntityRepository
{
}
